"""Add phase 3 detailed fields

Revision ID: 7fe7705ae759
Revises: 516b1a19c9f0
Create Date: 2026-09-12 23:16:11.847131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe7705ae759'
down_revision: Union[str, Sequence[str], None] = '516b1a19c9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_experiences', sa.Column('technologies', sa.Text(), nullable=True))
    op.add_column('career_experiences', sa.Column('achievements', sa.Text(), nullable=True))
    op.add_column('career_experiences', sa.Column('problems_solved', sa.Text(), nullable=True))
    op.add_column('certifications', sa.Column('related_skills', sa.Text(), nullable=True))
    op.add_column('education', sa.Column('subjects', sa.Text(), nullable=True))
    op.add_column('education', sa.Column('academic_projects', sa.Text(), nullable=True))
    op.add_column('education', sa.Column('courses', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('technologies', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('responsibilities', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('architecture', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('repository_url', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('deployment_url', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('lessons_learned', sa.Text(), nullable=True))
    op.add_column('skills', sa.Column('familiarity', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('professional_summary', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('current_role', sa.String(length=150), nullable=True))
    op.add_column('user_profiles', sa.Column('career_start_date', sa.Date(), nullable=True))
    op.add_column('user_profiles', sa.Column('career_interests', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('target_roles', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('portfolio_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'portfolio_url')
    op.drop_column('user_profiles', 'target_roles')
    op.drop_column('user_profiles', 'career_interests')
    op.drop_column('user_profiles', 'career_start_date')
    op.drop_column('user_profiles', 'current_role')
    op.drop_column('user_profiles', 'professional_summary')
    op.drop_column('skills', 'familiarity')
    op.drop_column('projects', 'lessons_learned')
    op.drop_column('projects', 'deployment_url')
    op.drop_column('projects', 'repository_url')
    op.drop_column('projects', 'architecture')
    op.drop_column('projects', 'responsibilities')
    op.drop_column('projects', 'technologies')
    op.drop_column('education', 'courses')
    op.drop_column('education', 'academic_projects')
    op.drop_column('education', 'subjects')
    op.drop_column('certifications', 'related_skills')
    op.drop_column('career_experiences', 'problems_solved')
    op.drop_column('career_experiences', 'achievements')
    op.drop_column('career_experiences', 'technologies')
    # ### end Alembic commands ###
