"""Add personal knowledge fields

Revision ID: 8466646a5356
Revises: d4444444444d
Create Date: 2026-09-13 08:44:03.650760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8466646a5356'
down_revision: Union[str, Sequence[str], None] = 'd4444444444d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.String(length=100), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_hash', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('duplicates', sa.Integer(), nullable=True),
    sa.Column('validation_errors', sa.Integer(), nullable=True),
    sa.Column('review_required', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_audit_logs_id'), 'import_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_import_audit_logs_import_id'), 'import_audit_logs', ['import_id'], unique=True)
    op.add_column('career_experiences', sa.Column('organization_name', sa.String(length=150), nullable=True))
    op.add_column('career_experiences', sa.Column('domain', sa.String(length=100), nullable=True))
    op.add_column('career_experiences', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('career_experiences', sa.Column('confidence', sa.String(length=50), nullable=True))
    op.add_column('career_experiences', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('career_experiences', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('certifications', sa.Column('code', sa.String(length=100), nullable=True))
    op.add_column('certifications', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('certifications', sa.Column('verification_status', sa.String(length=50), nullable=True))
    op.add_column('certifications', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('education', sa.Column('qualification', sa.String(length=150), nullable=True))
    op.add_column('education', sa.Column('result', sa.String(length=100), nullable=True))
    op.add_column('education', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('education', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('education', sa.Column('confidence', sa.String(length=50), nullable=True))
    op.add_column('evidence', sa.Column('evidence_type', sa.String(length=100), nullable=True))
    op.add_column('evidence', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('evidence', sa.Column('verification_status', sa.String(length=50), nullable=True))
    op.add_column('evidence', sa.Column('confidence', sa.String(length=50), nullable=True))
    op.add_column('skills', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('skills', sa.Column('assessment_status', sa.String(length=50), nullable=True))
    op.add_column('skills', sa.Column('confidence', sa.String(length=50), nullable=True))
    op.add_column('skills', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('professional_identity', sa.String(length=150), nullable=True))
    op.add_column('user_profiles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_profiles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'updated_at')
    op.drop_column('user_profiles', 'created_at')
    op.drop_column('user_profiles', 'professional_identity')
    op.drop_column('user_profiles', 'display_name')
    op.drop_column('skills', 'score')
    op.drop_column('skills', 'confidence')
    op.drop_column('skills', 'assessment_status')
    op.drop_column('skills', 'status')
    op.drop_column('evidence', 'confidence')
    op.drop_column('evidence', 'verification_status')
    op.drop_column('evidence', 'source')
    op.drop_column('evidence', 'evidence_type')
    op.drop_column('education', 'confidence')
    op.drop_column('education', 'source')
    op.drop_column('education', 'year')
    op.drop_column('education', 'result')
    op.drop_column('education', 'qualification')
    op.drop_column('certifications', 'source')
    op.drop_column('certifications', 'verification_status')
    op.drop_column('certifications', 'status')
    op.drop_column('certifications', 'code')
    op.drop_column('career_experiences', 'updated_at')
    op.drop_column('career_experiences', 'created_at')
    op.drop_column('career_experiences', 'confidence')
    op.drop_column('career_experiences', 'source')
    op.drop_column('career_experiences', 'domain')
    op.drop_column('career_experiences', 'organization_name')
    op.drop_index(op.f('ix_import_audit_logs_import_id'), table_name='import_audit_logs')
    op.drop_index(op.f('ix_import_audit_logs_id'), table_name='import_audit_logs')
    op.drop_table('import_audit_logs')
    # ### end Alembic commands ###
